[custom]
; 不要随意改变关键字，否则会导致出错
; ACL4SSR 规则

; 规则集（保持原有规则）
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=📲 TGSU,https://raw.githubusercontent.com/xu348025782/csguize/main/TGSU.list
ruleset=🎥 TGDL,https://raw.githubusercontent.com/xu348025782/csguize/main/TGDL.list
ruleset=🎶 TikTok,https://raw.githubusercontent.com/xu348025782/csguize/main/TikTok.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL


; 代理组
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇩🇪 德国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点
custom_proxy_group=📲 TGSU`select`[]🚀 节点选择`[]🇩🇪 德国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点
custom_proxy_group=🎥 TGDL`select`[]🚀 节点选择`[]🇩🇪 德国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点
custom_proxy_group=🎶 TikTok`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇩🇪 德国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇩🇪 德国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点
custom_proxy_group=🌏 国内媒体`select`[]DIRECT
custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=🛑 广告拦截`select`[]REJECT
custom_proxy_group=🍃 应用净化`select`[]REJECT

; 地区代理组
# 地区节点分组
custom_proxy_group=🇭🇰 香港节点`url-test`(HK|Hong|HGC|港)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡节点`url-test`(SG|Singapore|新加坡)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇩🇪 德国节点`url-test`(DE|Germany|DEU|德国)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|东京|JP|Japan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=其他节点`select`^(?!.*(HK|Hong|HGC|港|SG|Singapore|新加坡|DE|Germany|DEU|德国|日本|东京|JP|Japan)).*

; 规则生成器设置
enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml
